#!/bin/bash

# Build pato-twitch plugin
cd pato-twitch
wkg wit fetch
cargo build --release --target wasm32-wasip2 

# Copy plugins
cd ..
mkdir -p src-tauri/plugins/pato_twitch_0_1_0
cp pato-twitch/target/wasm32-wasip2/release/pato_twitch.wasm src-tauri/plugins/pato_twitch_0_1_0/pato_twitch.wasm

# Build UI
esbuild src-ui/pato.ts --bundle --sourcemap --outfile=src-ui/index.js

# Run application
cargo tauri dev --no-watch